package com.bielu.oshift.service.protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CrimeList.proto

public final class CrimesProto {
  private CrimesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CrimeListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CrimeList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    java.util.List<CrimesProto.CrimeList.Crime> 
        getCrimesList();
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    CrimesProto.CrimeList.Crime getCrimes(int index);
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    int getCrimesCount();
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    java.util.List<? extends CrimesProto.CrimeList.CrimeOrBuilder> 
        getCrimesOrBuilderList();
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    CrimesProto.CrimeList.CrimeOrBuilder getCrimesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CrimeList}
   */
  public static final class CrimeList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CrimeList)
      CrimeListOrBuilder {
    // Use CrimeList.newBuilder() to construct.
    private CrimeList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CrimeList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CrimeList defaultInstance;
    public static CrimeList getDefaultInstance() {
      return defaultInstance;
    }

    public CrimeList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CrimeList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                crimes_ = new java.util.ArrayList<CrimesProto.CrimeList.Crime>();
                mutable_bitField0_ |= 0x00000001;
              }
              crimes_.add(input.readMessage(CrimesProto.CrimeList.Crime.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          crimes_ = java.util.Collections.unmodifiableList(crimes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CrimesProto.internal_static_CrimeList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CrimesProto.internal_static_CrimeList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CrimesProto.CrimeList.class, CrimesProto.CrimeList.Builder.class);
    }

    public static com.google.protobuf.Parser<CrimeList> PARSER =
        new com.google.protobuf.AbstractParser<CrimeList>() {
      public CrimeList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CrimeList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CrimeList> getParserForType() {
      return PARSER;
    }

    public interface CrimeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CrimeList.Crime)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string uuid = 1;</code>
       */
      boolean hasUuid();
      /**
       * <code>optional string uuid = 1;</code>
       */
      java.lang.String getUuid();
      /**
       * <code>optional string uuid = 1;</code>
       */
      com.google.protobuf.ByteString
          getUuidBytes();

      /**
       * <code>optional string title = 2;</code>
       */
      boolean hasTitle();
      /**
       * <code>optional string title = 2;</code>
       */
      java.lang.String getTitle();
      /**
       * <code>optional string title = 2;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <code>optional bool solved = 3;</code>
       */
      boolean hasSolved();
      /**
       * <code>optional bool solved = 3;</code>
       */
      boolean getSolved();

      /**
       * <code>optional string date = 4;</code>
       */
      boolean hasDate();
      /**
       * <code>optional string date = 4;</code>
       */
      java.lang.String getDate();
      /**
       * <code>optional string date = 4;</code>
       */
      com.google.protobuf.ByteString
          getDateBytes();
    }
    /**
     * Protobuf type {@code CrimeList.Crime}
     */
    public static final class Crime extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:CrimeList.Crime)
        CrimeOrBuilder {
      // Use Crime.newBuilder() to construct.
      private Crime(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Crime(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Crime defaultInstance;
      public static Crime getDefaultInstance() {
        return defaultInstance;
      }

      public Crime getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Crime(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                uuid_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                title_ = bs;
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                solved_ = input.readBool();
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                date_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CrimesProto.internal_static_CrimeList_Crime_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CrimesProto.internal_static_CrimeList_Crime_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CrimesProto.CrimeList.Crime.class, CrimesProto.CrimeList.Crime.Builder.class);
      }

      public static com.google.protobuf.Parser<Crime> PARSER =
          new com.google.protobuf.AbstractParser<Crime>() {
        public Crime parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Crime(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Crime> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int UUID_FIELD_NUMBER = 1;
      private java.lang.Object uuid_;
      /**
       * <code>optional string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TITLE_FIELD_NUMBER = 2;
      private java.lang.Object title_;
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SOLVED_FIELD_NUMBER = 3;
      private boolean solved_;
      /**
       * <code>optional bool solved = 3;</code>
       */
      public boolean hasSolved() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool solved = 3;</code>
       */
      public boolean getSolved() {
        return solved_;
      }

      public static final int DATE_FIELD_NUMBER = 4;
      private java.lang.Object date_;
      /**
       * <code>optional string date = 4;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string date = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        uuid_ = "";
        title_ = "";
        solved_ = false;
        date_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getUuidBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTitleBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBool(3, solved_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getDateBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUuidBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTitleBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, solved_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getDateBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static CrimesProto.CrimeList.Crime parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CrimesProto.CrimeList.Crime parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CrimesProto.CrimeList.Crime parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CrimesProto.CrimeList.Crime parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CrimesProto.CrimeList.Crime parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static CrimesProto.CrimeList.Crime parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static CrimesProto.CrimeList.Crime parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static CrimesProto.CrimeList.Crime parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static CrimesProto.CrimeList.Crime parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static CrimesProto.CrimeList.Crime parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(CrimesProto.CrimeList.Crime prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CrimeList.Crime}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CrimeList.Crime)
          CrimesProto.CrimeList.CrimeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CrimesProto.internal_static_CrimeList_Crime_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CrimesProto.internal_static_CrimeList_Crime_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CrimesProto.CrimeList.Crime.class, CrimesProto.CrimeList.Crime.Builder.class);
        }

        // Construct using Crimes.CrimeList.Crime.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          uuid_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          title_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          solved_ = false;
          bitField0_ = (bitField0_ & ~0x00000004);
          date_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CrimesProto.internal_static_CrimeList_Crime_descriptor;
        }

        public CrimesProto.CrimeList.Crime getDefaultInstanceForType() {
          return CrimesProto.CrimeList.Crime.getDefaultInstance();
        }

        public CrimesProto.CrimeList.Crime build() {
          CrimesProto.CrimeList.Crime result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public CrimesProto.CrimeList.Crime buildPartial() {
          CrimesProto.CrimeList.Crime result = new CrimesProto.CrimeList.Crime(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.uuid_ = uuid_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.title_ = title_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.solved_ = solved_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.date_ = date_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CrimesProto.CrimeList.Crime) {
            return mergeFrom((CrimesProto.CrimeList.Crime)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CrimesProto.CrimeList.Crime other) {
          if (other == CrimesProto.CrimeList.Crime.getDefaultInstance()) return this;
          if (other.hasUuid()) {
            bitField0_ |= 0x00000001;
            uuid_ = other.uuid_;
            onChanged();
          }
          if (other.hasTitle()) {
            bitField0_ |= 0x00000002;
            title_ = other.title_;
            onChanged();
          }
          if (other.hasSolved()) {
            setSolved(other.getSolved());
          }
          if (other.hasDate()) {
            bitField0_ |= 0x00000008;
            date_ = other.date_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CrimesProto.CrimeList.Crime parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CrimesProto.CrimeList.Crime) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object uuid_ = "";
        /**
         * <code>optional string uuid = 1;</code>
         */
        public boolean hasUuid() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string uuid = 1;</code>
         */
        public java.lang.String getUuid() {
          java.lang.Object ref = uuid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              uuid_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string uuid = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUuidBytes() {
          java.lang.Object ref = uuid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uuid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string uuid = 1;</code>
         */
        public Builder setUuid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          uuid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string uuid = 1;</code>
         */
        public Builder clearUuid() {
          bitField0_ = (bitField0_ & ~0x00000001);
          uuid_ = getDefaultInstance().getUuid();
          onChanged();
          return this;
        }
        /**
         * <code>optional string uuid = 1;</code>
         */
        public Builder setUuidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          uuid_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object title_ = "";
        /**
         * <code>optional string title = 2;</code>
         */
        public boolean hasTitle() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              title_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder clearTitle() {
          bitField0_ = (bitField0_ & ~0x00000002);
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>optional string title = 2;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          title_ = value;
          onChanged();
          return this;
        }

        private boolean solved_ ;
        /**
         * <code>optional bool solved = 3;</code>
         */
        public boolean hasSolved() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional bool solved = 3;</code>
         */
        public boolean getSolved() {
          return solved_;
        }
        /**
         * <code>optional bool solved = 3;</code>
         */
        public Builder setSolved(boolean value) {
          bitField0_ |= 0x00000004;
          solved_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool solved = 3;</code>
         */
        public Builder clearSolved() {
          bitField0_ = (bitField0_ & ~0x00000004);
          solved_ = false;
          onChanged();
          return this;
        }

        private java.lang.Object date_ = "";
        /**
         * <code>optional string date = 4;</code>
         */
        public boolean hasDate() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string date = 4;</code>
         */
        public java.lang.String getDate() {
          java.lang.Object ref = date_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              date_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string date = 4;</code>
         */
        public com.google.protobuf.ByteString
            getDateBytes() {
          java.lang.Object ref = date_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            date_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string date = 4;</code>
         */
        public Builder setDate(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          date_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string date = 4;</code>
         */
        public Builder clearDate() {
          bitField0_ = (bitField0_ & ~0x00000008);
          date_ = getDefaultInstance().getDate();
          onChanged();
          return this;
        }
        /**
         * <code>optional string date = 4;</code>
         */
        public Builder setDateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          date_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:CrimeList.Crime)
      }

      static {
        defaultInstance = new Crime(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:CrimeList.Crime)
    }

    public static final int CRIMES_FIELD_NUMBER = 1;
    private java.util.List<CrimesProto.CrimeList.Crime> crimes_;
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    public java.util.List<CrimesProto.CrimeList.Crime> getCrimesList() {
      return crimes_;
    }
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    public java.util.List<? extends CrimesProto.CrimeList.CrimeOrBuilder> 
        getCrimesOrBuilderList() {
      return crimes_;
    }
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    public int getCrimesCount() {
      return crimes_.size();
    }
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    public CrimesProto.CrimeList.Crime getCrimes(int index) {
      return crimes_.get(index);
    }
    /**
     * <code>repeated .CrimeList.Crime crimes = 1;</code>
     */
    public CrimesProto.CrimeList.CrimeOrBuilder getCrimesOrBuilder(
        int index) {
      return crimes_.get(index);
    }

    private void initFields() {
      crimes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < crimes_.size(); i++) {
        output.writeMessage(1, crimes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < crimes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, crimes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CrimesProto.CrimeList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CrimesProto.CrimeList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CrimesProto.CrimeList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CrimesProto.CrimeList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CrimesProto.CrimeList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CrimesProto.CrimeList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CrimesProto.CrimeList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CrimesProto.CrimeList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CrimesProto.CrimeList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CrimesProto.CrimeList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CrimesProto.CrimeList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CrimeList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CrimeList)
        CrimesProto.CrimeListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CrimesProto.internal_static_CrimeList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CrimesProto.internal_static_CrimeList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CrimesProto.CrimeList.class, CrimesProto.CrimeList.Builder.class);
      }

      // Construct using Crimes.CrimeList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCrimesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (crimesBuilder_ == null) {
          crimes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          crimesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CrimesProto.internal_static_CrimeList_descriptor;
      }

      public CrimesProto.CrimeList getDefaultInstanceForType() {
        return CrimesProto.CrimeList.getDefaultInstance();
      }

      public CrimesProto.CrimeList build() {
        CrimesProto.CrimeList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CrimesProto.CrimeList buildPartial() {
        CrimesProto.CrimeList result = new CrimesProto.CrimeList(this);
        if (crimesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            crimes_ = java.util.Collections.unmodifiableList(crimes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.crimes_ = crimes_;
        } else {
          result.crimes_ = crimesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CrimesProto.CrimeList) {
          return mergeFrom((CrimesProto.CrimeList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CrimesProto.CrimeList other) {
        if (other == CrimesProto.CrimeList.getDefaultInstance()) return this;
        if (crimesBuilder_ == null) {
          if (!other.crimes_.isEmpty()) {
            if (crimes_.isEmpty()) {
              crimes_ = other.crimes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCrimesIsMutable();
              crimes_.addAll(other.crimes_);
            }
            onChanged();
          }
        } else {
          if (!other.crimes_.isEmpty()) {
            if (crimesBuilder_.isEmpty()) {
              crimesBuilder_.dispose();
              crimesBuilder_ = null;
              crimes_ = other.crimes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              crimesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCrimesFieldBuilder() : null;
            } else {
              crimesBuilder_.addAllMessages(other.crimes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CrimesProto.CrimeList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CrimesProto.CrimeList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<CrimesProto.CrimeList.Crime> crimes_ =
        java.util.Collections.emptyList();
      private void ensureCrimesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          crimes_ = new java.util.ArrayList<CrimesProto.CrimeList.Crime>(crimes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          CrimesProto.CrimeList.Crime, CrimesProto.CrimeList.Crime.Builder, CrimesProto.CrimeList.CrimeOrBuilder> crimesBuilder_;

      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public java.util.List<CrimesProto.CrimeList.Crime> getCrimesList() {
        if (crimesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(crimes_);
        } else {
          return crimesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public int getCrimesCount() {
        if (crimesBuilder_ == null) {
          return crimes_.size();
        } else {
          return crimesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public CrimesProto.CrimeList.Crime getCrimes(int index) {
        if (crimesBuilder_ == null) {
          return crimes_.get(index);
        } else {
          return crimesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder setCrimes(
          int index, CrimesProto.CrimeList.Crime value) {
        if (crimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCrimesIsMutable();
          crimes_.set(index, value);
          onChanged();
        } else {
          crimesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder setCrimes(
          int index, CrimesProto.CrimeList.Crime.Builder builderForValue) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.set(index, builderForValue.build());
          onChanged();
        } else {
          crimesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder addCrimes(CrimesProto.CrimeList.Crime value) {
        if (crimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCrimesIsMutable();
          crimes_.add(value);
          onChanged();
        } else {
          crimesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder addCrimes(
          int index, CrimesProto.CrimeList.Crime value) {
        if (crimesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCrimesIsMutable();
          crimes_.add(index, value);
          onChanged();
        } else {
          crimesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder addCrimes(
          CrimesProto.CrimeList.Crime.Builder builderForValue) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.add(builderForValue.build());
          onChanged();
        } else {
          crimesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder addCrimes(
          int index, CrimesProto.CrimeList.Crime.Builder builderForValue) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.add(index, builderForValue.build());
          onChanged();
        } else {
          crimesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder addAllCrimes(
          java.lang.Iterable<? extends CrimesProto.CrimeList.Crime> values) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, crimes_);
          onChanged();
        } else {
          crimesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder clearCrimes() {
        if (crimesBuilder_ == null) {
          crimes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          crimesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public Builder removeCrimes(int index) {
        if (crimesBuilder_ == null) {
          ensureCrimesIsMutable();
          crimes_.remove(index);
          onChanged();
        } else {
          crimesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public CrimesProto.CrimeList.Crime.Builder getCrimesBuilder(
          int index) {
        return getCrimesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public CrimesProto.CrimeList.CrimeOrBuilder getCrimesOrBuilder(
          int index) {
        if (crimesBuilder_ == null) {
          return crimes_.get(index);  } else {
          return crimesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public java.util.List<? extends CrimesProto.CrimeList.CrimeOrBuilder> 
           getCrimesOrBuilderList() {
        if (crimesBuilder_ != null) {
          return crimesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(crimes_);
        }
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public CrimesProto.CrimeList.Crime.Builder addCrimesBuilder() {
        return getCrimesFieldBuilder().addBuilder(
            CrimesProto.CrimeList.Crime.getDefaultInstance());
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public CrimesProto.CrimeList.Crime.Builder addCrimesBuilder(
          int index) {
        return getCrimesFieldBuilder().addBuilder(
            index, CrimesProto.CrimeList.Crime.getDefaultInstance());
      }
      /**
       * <code>repeated .CrimeList.Crime crimes = 1;</code>
       */
      public java.util.List<CrimesProto.CrimeList.Crime.Builder> 
           getCrimesBuilderList() {
        return getCrimesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CrimesProto.CrimeList.Crime, CrimesProto.CrimeList.Crime.Builder, CrimesProto.CrimeList.CrimeOrBuilder> 
          getCrimesFieldBuilder() {
        if (crimesBuilder_ == null) {
          crimesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CrimesProto.CrimeList.Crime, CrimesProto.CrimeList.Crime.Builder, CrimesProto.CrimeList.CrimeOrBuilder>(
                  crimes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          crimes_ = null;
        }
        return crimesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:CrimeList)
    }

    static {
      defaultInstance = new CrimeList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CrimeList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrimeList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrimeList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CrimeList_Crime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CrimeList_Crime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CrimeList.proto\"q\n\tCrimeList\022 \n\006crimes" +
      "\030\001 \003(\0132\020.CrimeList.Crime\032B\n\005Crime\022\014\n\004uui" +
      "d\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\016\n\006solved\030\003 \001(\010\022\014" +
      "\n\004date\030\004 \001(\tB\010B\006Crimes"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CrimeList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CrimeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CrimeList_descriptor,
        new java.lang.String[] { "Crimes", });
    internal_static_CrimeList_Crime_descriptor =
      internal_static_CrimeList_descriptor.getNestedTypes().get(0);
    internal_static_CrimeList_Crime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CrimeList_Crime_descriptor,
        new java.lang.String[] { "Uuid", "Title", "Solved", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
